[package]
name = "tc-utils"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clipboard-win = "5.3.0"
encoding_rs = "0.8.33"
encoding_rs_io = "0.1.7"
rand = "0.8.5"
regex = "1.10.4"
